<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>1.4.1</Version>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <Authors>Gu5</Authors>
    <Company>Gu5</Company>
    <Copyright>Gu5</Copyright>
    <Description>.NET 通用库
.NET universal library</Description>
    <PackageId>Gu5.Core</PackageId>
    <PackageLicenseUrl />
    <PackageProjectUrl>https://github.com/Kyufuru/Gu5.Net</PackageProjectUrl>
    <PackageReleaseNotes>feat: reflection - GetInstancesOf&lt;T&gt;</PackageReleaseNotes>
    <PackageTags>gu5</PackageTags>
    <Product>Gu5.Core</Product>
    <RepositoryType />
    <RepositoryUrl>https://github.com/Kyufuru/Gu5.Net.git</RepositoryUrl>
    <ProduceReferenceAssembly>True</ProduceReferenceAssembly>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <SignAssembly>False</SignAssembly>
    <Title>谷雨</Title>
    <NeutralLanguage>zh-CN</NeutralLanguage>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <IncludeSymbols>False</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <Name />
    <PackageIconUrl />
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <BaseOutputPath>D:\Code\Build\Gu5\Gu5.Core</BaseOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>none</DebugType>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bin\**" />
    <EmbeddedResource Remove="bin\**" />
    <None Remove="bin\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Flurl" Version="4.0.0" />
    <PackageReference Include="Flurl.Http" Version="4.0.2" />
  </ItemGroup>

</Project>
