<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <PackageIcon>icon.png</PackageIcon>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <Authors>Gu5</Authors>
    <Company>Gu5</Company>
    <Copyright>Gu5</Copyright>
    <Description>.NET 通用库
.NET universal library</Description>
    <PackageId>Gu5.Core</PackageId>
    <PackageLicenseUrl />
    <PackageProjectUrl>https://github.com/Kyufuru/Gu5.Net</PackageProjectUrl>
    <PackageReleaseNotes>feat: SetValue - set property for generic type</PackageReleaseNotes>
    <PackageTags>gu5</PackageTags>
    <Product>Gu5.Core</Product>
    <RepositoryType />
    <RepositoryUrl>https://github.com/Kyufuru/Gu5.Net.git</RepositoryUrl>
    <Version>1.4.0</Version>
    <ProduceReferenceAssembly>True</ProduceReferenceAssembly>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <SignAssembly>False</SignAssembly>
    <Title>谷雨</Title>
    <NeutralLanguage>zh-CN</NeutralLanguage>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <IncludeSymbols>False</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <Name />
    <PackageIconUrl />
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>none</DebugType>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="icon.png" />
    <None Remove="README.md" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </Content>
    <Content Include="readme.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.2" />
  </ItemGroup>

</Project>
